{% set name = "fastimport" %}
{% set version = "0.9.8" %}
{% set sha256 = "b2f2e8eb97000256e1aab83d2a0a053fc7b93c3aa4f7e9b971a5703dfc5963b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install 

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - fastimport
    - fastimport.tests
    - fastimport.processors

about:
  home: https://github.com/jelmer/python-fastimport
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'VCS fastimport/fastexport parser'

  description: |
    This package provides a parser for and generator of the Git fastimport format.
  doc_url: https://www.kernel.org/pub/software/scm/git/docs/git-fast-import.html
  dev_url: https://github.com/jelmer/python-fastimport

extra:
  recipe-maintainers:
    - mikofski
