{% set name = "fastimport" %}
{% set version = "0.9.9" %}
{% set sha256 = "94ae89ad0d76914c396eed3bb904551131ee579b0c58f9efe8bda5fa3009f319" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - fastimport
    - fastimport.tests
    - fastimport.processors

about:
  home: https://github.com/jelmer/python-fastimport
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: VCS fastimport/fastexport parser

  description: |
    This package provides a parser for and generator of the Git fastimport format.
  doc_url: https://www.kernel.org/pub/software/scm/git/docs/git-fast-import.html
  dev_url: https://github.com/jelmer/python-fastimport

extra:
  recipe-maintainers:
    - mikofski
