{% set name = "fastimport" %}
{% set version = "0.9.14" %}
{% set sha256 = "6ac99dda4e7b0b3ae831507b6d0094802e6dd95891feafde8cc5c405b6c149ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - fastimport
    - fastimport.tests
    - fastimport.processors

about:
  home: https://github.com/jelmer/python-fastimport
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: VCS fastimport/fastexport parser

  description: |
    This package provides a parser for and generator of the Git fastimport format.
  doc_url: https://www.kernel.org/pub/software/scm/git/docs/git-fast-import.html
  dev_url: https://github.com/jelmer/python-fastimport

extra:
  recipe-maintainers:
    - mikofski
