travis:
  secure:
    BINSTAR_TOKEN: KIXmEcKwvFq8HlEt5cii0WBhDoJSbJJlO756pMFEc1KZVT0ioWHisnu3OC2EX878x4aPx5yBFjnndLaOKmnZ4aymP9Pz25Tq0xjmDrNx8pnzgQ/BEcULkH0hU4FxBoxINoyCpafdUCN+ZrtpkB9ClTHhadmZDde8RkYa6Y3aTm+N67jFsPikAgWq5CWtOY2SWkVA1Rz5aO6IGaLk1jswzKL52bCagaTYSDlncWGtNg+nkLYvrP70kx4rdRVzxtESsbLROz4PzE3VnOen4eo8lnEIQCUWb+po0EYk2ADBsA7+LGQWrHgQSb0pmNl3haZi0lvbI1/xfqcGqQ610d3iPqle/Z9cSN4j67YyiKlB+lUympQ10t0QvqSd8jikk+XO7JmzK88QbVrduHuC+SzlgaAfUnuw1ySuXO01HqlneDy+MhLOpCFiCslcOQtFzf9HWYnJqSZPsQkcQoBkELErfdHCMG5qOyKv3N6am6speqB2TKXKUWqVMywgQegXDxc6GexxhKGBlN7x2p9dRIs1jyiJy1JrBIREd/9EKpQvZWgoNXlCN04oRAZ0gTVl/A86P4e3zV1SCeCjWAYF+KXpuLoyzPfHA5jyQeDpP+a9epCgMTAjVeDMJsFptbQxDedfs+l3u1nnZPAhUu505NRrmPyOgoGCcICKTURtjmSQuyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
