travis:
  secure:
    BINSTAR_TOKEN: Wz1Zx1yFCSYbqkrgez/6lluKBfFRA5NH0eHW2o/UyDZafxN06DfmryoC7my50YVMOb6KP9Eg5aCQKXd2L36mIpo1irXKwMB7WcNo7EeILhZLYK1nN4hBTcxEsKF5y7NrrPuVg8zHsnwh13rW9ZBQfL1ArOIy2fAy0SdxDvDoaq3Fb7fi+og8OhGGi9DswgAhHHq+m4HwgC6zRM8/QWnsXV1QaMACOSvD5h2SAsKqjB4Ov+XGeAfccrPFn6eMYiqPpz54d981MCsDebM1uT77zLQf3gpMaS1iR6H/HcNdFdYbomtOeL53l4mmLTuYiZFmE63kE1rRyKiZaW8ApXhwIgJfP+pfhkco5dF6/kJ3vKzIfgs+164hQ/PfnyBkyqmeJtYQAivybBqVdTo2quKEtJ12ULkKEFUBi5716hv8kVOA0jhpgts4OzPZAsVAkYZtb5r2Qh6+dPhTtBMYeYJTd5qBub52vLGjf3ZimGzWcgc0nNxSv3pvCfhvzNokMojQzU/RS5x5+nrWKqrtUQ6INeBalzL0eZTpBHMi9w2Tk2tD00ulMtqmcWRvBKsUCMFe2P3iufYtSkt/IwTvlGj1sc5WbJ5tetHTytCpTDqSyOdzZ3mSc1Yk44vrf1EaVclT19FJSOg62NlxJy6LHBbhz6L9E4XhkzC1Z7AsX+FAV+8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
