travis:
  secure:
    BINSTAR_TOKEN: 2y9PhdLbCqCckMkYArULIune1v98Cr4giLMY930dEGXJjavd9RUCFGIJ6gKJe7Kk/VymWZLPe4IG6MNi6ZM9TslR16/xJep2iIAQjYg47CuWdaOASpVkFb+odMNWsMgnXROP9O2uOnCW2cr/PxHKDSTsc2Yvbvmf7M7rhyo94/6CDF7bqXhNqD3K3D+DUmlHNoCemJvIRN0s1knOCU4Nn30ASuiqZycL2LRC1vQ1V37AzjO7cOCWnvfY0dDQFOld5QJ1tDx9xlPwSBhbTKkw9aCdDbeQ/Y5hvGpm/XMux0th/SPWAlr1DzpMRVYLssC2Ng0F8ikLu5fVkeTCDlusWaPkrnx4+1Tkw2RXd6TIxfyb0fBsM0/SsFWgkL9bfI+B4bQFewgodtjOlPnZF4+sgpiZ2YrVgi4DP0xvuygJsPuBL+qQ/B84vnXHXUS6v+lu/b96QzTmUSnJUyN1sX5umWojKJYg5QZ19moCXKfAKP5u+IsaQIdOWdH02DrU6CsUCtTy1mjXdGrlR95H72nVqQszuNcwMe/XTBK7CdYvafxHFx2OMeOuI1MFOd+dtM5W5Mi78fgJw599zpIHwrnGCkTL3Zsyr97961ehgXxO0Uh6Ty5iZUhT62HTFwotW1ZtqiFkWkAWQrnHHuCcXPCtPlcvtv1nSPIkw71lzfl0ubU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
