travis:
  secure:
    BINSTAR_TOKEN: YM6SBen8XCoDB+gBhVK1QpKyMwR6IoQmbqz+/A0aYGgzgoSEx1BwVZ+6avJw5MV1x56DOZZ7QDA8wpWLchFk/WLJG6wX4QvNp3vgMxnbV+2Upkh4dDI8no/uG+XysgMAvPpKzW1OrzVqRMh+RQm520DzCpsg9aFag4VdVHxpQ8FhI9wS2WEVPFwfuItSHgWXOXxG70hFa8qgFAbw/JUDFbBuBJk+QCZHq024fImAle/MbqTypcDGuu0rZxWqrYBzcS3F0Cw/3nXCCORx2uZEbfHpe+l/V/F35RnQpYmnxsxoaZaHY0gov0jF9js1AdBMoD14ihdpBuvfsViRAvXB6rqvKIf4x6VjWuMdGzJYvwtNwU/Bz+hySmXArVAIbwcquIwlQGr+OuS4L2BxgI6YTrlnYCIcVl1RQwDpSOQMnhYrn+/2XJDrQ/5sn5oSSzcaCRvi6ufmaEcRO30+GpewfzGZxQ02prShkM0Jwp7GB1vQsq2OjyiYYgVLPNCB9EJA/k91h/vLGy4gMAlIz5C+FJ8lC4+HNum8Qm/lCTcpPpr9/taB4FzOSvWMuyMJMAKvcabn/Q4cKDeyysEABQmpJHSF8AERiT5Tw+MLTFWKbU9dHmBGWItGUuLN8WguF0/gBZMOcjz/iEc4cno1EGpjxlh5AGx5pYyPPA+Hn1wQFJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
