travis:
  secure:
    BINSTAR_TOKEN: 1XTyuxBDsHSmelNqRmh3NXQwA60spipZ50QXU0UCwwPey1Sa94gBrdMeSVo8z6IVvjp8jPH4VXm4EdfS/2rfU5WhlIQG3+Iyk7aFxmuUOAsHgfxDo4LuaLun1lojeN/whZDahEry3IPRa9OfvVYTNDHCu471uUSI1KfT/C4mjVeZBuqDrLLwQ/h2IMoZsAUSUJmZjgP8+pPd//u4R9JuYzIxNKRj1SFt29hMR6m0f7CBx3TXIMArNl3fyWjtVr1DmJlg14/ok1feaAY1WhNQg+d6mSdbu/zGu4MF2yKUPVbIHGHHzpwgcqJdXCV0Eol6qd9DjJKSRMGF/B3ciNo1y4U52KuLkNOTfx92qMLQlqMR5Hjg8Etz5o1Sr4HRoxJI4JWW/K9wiV0bdF+vWYiNZfvYLyhKboDwGHIdC48ENh3DO5TMNtmTbS5fS5daSMiDcmC/1e3Zd5JV9hpmVxkLBfL+WRU4gqTP+VMO1i48UcOOy0/tR4vCRWSHJ1C/2L2xrAByZiTPsLKOkO2xM6D5ph5AhJthrmWaoVqmwUUK0eb1gb4altQkhEJithZO39FSy86naacwbITnyZEQUWToeV5Xc20GbM0ni9E4df4LaY1Z5OM1vyyT/tpozOOj6UvJKS67hx2Fvw2jL6jn6A8UqhR3FeEE90Tgpo493zii178=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
