travis:
  secure:
    BINSTAR_TOKEN: llehTF0rMquAXER7TjyiPbzK0R88QqmtWTjmdCYezBqcOAjryebuH/4xKXUKyd9FQA6/2ZNd4+eRX2fUa7YrV4KzgxmryJbyWb+HDOMXxWDy5VxAzNAsJKTsQns5Zlgq0OP46ZXVxqcbnj33ul9eu9L0ZzX1fEREc85lBGNt7rQcwkUSpcZ0PnDUdonBlBUjQ/B2QQevQ/wHq/OkvKrh4qI8ICn5lyAulx0o/kDlylsRtI9Gbax92hpL8ZG2Om9RFKW4Nd6UtBVn8DS9wf2VJh99fX0NVK1HPyJ2+8QoCGd1RY+SYpIk6S5XhWxemVyespr/lgU/YQvgfgAajlPQDnw//amvEcp6f2xDcvkw+0EROFHBhIh4n2EG1+CvCcEm2UFu+zW4nVPRM5EvRuD9M96/Y7NjKTJ6LAfknQETcdOH9O++nCYtowpfFZp9XHpJTfhAoU8UEhR9za/U7uEDvZoX+vDnmcoW1drGTVeuLQHc3Ol5omZgX2cLyvAQVfMKANLzILLLClhM1GK+ayyuK3JfHjWMxttIlXM9+MJHcYRsSsQHWy2GifVxi7Qbq/eBwhVKH963QZ/QAvwcLKMgr5vmGaP22M7JHU07L8uvrev45TD+O/W5iyJ9AfWlWNtebbYO5AqWuXKQKUnQdHV2VpJnliLddbBT25rCYTzPWYI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
